---
title: "git_01"
author: "Jocelyn Lazcano"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


The lover, if for certain days  
His fair one be denied his gaze,  
Sinks not in grief and wild amaze,  
But, wiser wooer,  
He spends the time in writing lays  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


When the spent sun throws up its rays on cloud  
And goes down burning into the gulf below,  
No voice in nature is heard to cry aloud  
At what has happened. Birds, at least must know  
It is the change to darkness in the sky.  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  
      
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


The first story I ever write  
is a bright crayon picture  
of a dancing tree, the branches  
tossed by island wind.  

I draw myself standing beside the tree,  
with a colorful parrot soaring above me,  
and a magical turtle clasped in my hand,  

and two yellow wings fluttering  
on the proud shoulders of my ruffled  
Cuban rumba dancer's  
fancy dress.  


